spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
              spring.json.trusted.packages: "com.emkay.dto"
              spring.json.value.default.type: "com.emkay.dto.ProductEvent"  # ✅ your actual DTO class
              spring.json.use.type.headers: false
      